openapi: 3.0.0
info:
  title: Elbgoods Calendar API
  description: API for a simplified calendar application
  version: 0.1.0
  contact:
    email: christiandignas@gmail.com

servers:
  - url: /api/v1
    description: local server

paths:
  /appointments:
    get:
      summary: Returns a list of appointments
      parameters:
        - name: end_date
          in: query
          schema:
            format: date
            type: string
      responses:
        '200':
          description: A JSON array of appointments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentListResponse'
        '422':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    post:
      summary: create a new appointment
      requestBody:
        required: true
        description: post request
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "App presentation with Elbgoods"
                description:
                  type: string
                  example: "Presentation of calendar app with Elbgoods."
                start_date:
                  type: string
                  format: date
                  example: "2023-08-28"
                end_date:
                  type: string
                  format: date
                  example: "2023-08-28"
                status:
                  type: string
                  enum: ["Requested", "Tentative", "Booked"]
                  example: "Requested"
      responses:
        '201':
          description: A JSON object of a appointment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse'
        '422':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
  /appointments/{id}:
    parameters:
      - name: id
        in: path
        description: appointment id
        required: true
        schema:
          type: integer
          default: 10
    get:
      summary: get a appointment
      responses:
        '200':
          description: A JSON object of a appointment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse'
        '404':
          description: Appointment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentNotFound'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    put:
      summary: edit a appointment
      requestBody:
        required: true
        description: post request
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "App presentation with Elbgoods"
                description:
                  type: string
                  example: "Presentation of calendar app with Elbgoods."
                start_date:
                  type: string
                  format: date
                  example: "2023-08-28"
                end_date:
                  type: string
                  format: date
                  example: "2023-08-28"
                status:
                  type: string
                  enum: [ "Requested", "Tentative", "Booked" ]
                  example: "Requested"
      responses:
        '200':
          description: A JSON object of a appointment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentResponse'
        '404':
          description: Appointment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentNotFound'
        '422':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
    delete:
      summary: delete a appointment
      responses:
        '204':
          description: appointment deleted
        '404':
          description: Appointment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppointmentNotFound'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'
components:
  schemas:
    Appointment:
      type: object
      properties:
        id:
          type: integer
          description: id
          example: 1
        title:
          type: string
          description: title
          example: "App Presentation with Elbgoods"
        description:
          type: string
          description: description
          example: "App Presentation with Elbgoods."
        start_date:
          type: string
          description: start date
          format: date
          example: "2023-08-27"
        end_date:
          type: string
          description: start date
          format: date
          example: "2023-08-27"
        status:
          type: string
          description: status
          enum: [ "Requested", "Tentative", "Booked" ]
          example: "Requested"
    AppointmentResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Appointment'
    AppointmentListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Appointment'
    AppointmentNotFound:
      type: object
      description: Appointment not found
      properties:
        message:
          type: string
          description: error message
          example: Appointment not found.
    UnprocessableEntityError:
      type: object
      description: Internal Server Error
      properties:
        message:
          type: string
          description: error message
          example: Validation Error.
    InternalServerError:
      type: object
      description: Internal Server Error
      properties:
        message:
          type: string
          description: error message
          example: Internal Server Error.
