openapi: 3.0.0
info:
  title: Elbgoods Calendar API
  description: a simplified calendar application
  version: 0.1.9

servers:
  - url: http://localhost/api
    description: local server

paths:
  /calendar:
    get:
      summary: Returns a list of appointments
      responses:
        '200':
          description: A JSON array of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: create a new appointment
      responses:
        '200':
          description: A JSON array of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    patch:
      summary: edit a appointment
      responses:
        '200':
          description: A JSON array of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    delete:
      summary: delete a appointment
      responses:
        '200':
          description: A JSON array of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
